Ephemeris service
lsst-sssc/ssoforcedphot pull request #11
Opened 2024-07-23 13:02 UTC by szilac

## Change Description
The branch contains the full ephemeris service component. ephemeris_client.py controls the various interfaces. The outputs are uniformized. Each QueryResult returns a dataclass object or a QueryResult list. 

Fixed issues:
--> closes https://github.com/lsst-sssc/ssoforcedphot/issues/6
--> closes https://github.com/lsst-sssc/ssoforcedphot/issues/7
--> closes https://github.com/lsst-sssc/ssoforcedphot/issues/8
--> closes https://github.com/lsst-sssc/ssoforcedphot/issues/10

### New Feature Checklist
- Now it is a complete ephemeris service. One can call the ephemeris_client.py with args and control the different interfaces, like JPL Horizons, Miriade, custom data loader
- All of the relevant methods contains save_data options (default: False)

### Documentation Change Checklist
- Updated most of the docstring

2024-07-23 17:35 UTC, mschwamb commented
I think data directory should go under tests

2024-07-23 17:39 UTC, mschwamb commented
Discussion from the telecon is that ecsv handling is going to be updated

2024-07-24 19:58 UTC, mkelley reviewed
Some initial comments.  I will review more later.

2024-07-24 19:58 UTC, mkelley commented on src/forcedphot/ephemeris/local_dataclasses.py
> +        datetime_jd (Time): Julian date times for the ephemeris data points.
Since this is a time object, wouldn't this be better as:

`datetime (Time): Time for the ephemeris data points`

In other words, rename it to `datetime` and drop the description of the time format.

2024-07-24 19:58 UTC, mkelley commented on src/forcedphot/ephemeris/local_dataclasses.py
> +from dataclasses import dataclass, field
Recommend renaming this file "data_model.py"  I think we discussed this in a previous meeting.

2024-07-24 19:58 UTC, mkelley commented on src/forcedphot/ephemeris/horizons_interface.py
> +                "datetime_jd": ephemeris_data.datetime_jd.jd,
Will we save in UTC, TAI, or TDB?  It should be specified here, e.g., `ephemeris_data.datetime_jd.tai.jd`

2024-07-24 19:58 UTC, mkelley commented on src/forcedphot/ephemeris/data_loader.py
> +                datetime_jd=Time(table["datetime_jd"], format="jd"),
Is the file expected to be in UTC, TAI, or TDB?  It should be specified here in the Time object initialization with, e.g.,  `scale="tai"`.

2024-07-24 19:58 UTC, mkelley commented on src/forcedphot/ephemeris/horizons_interface.py
> +                        closest_apparition=True, no_fragments=True, skip_daylight=True
To ensure the most relevant comet orbit is used:
```
jd_mid = (start + (end - start) / 2).jd
...
closest_apparition=f"<{jd_mid:.0f}"
...
```
Here I used the mid point of the time request, but that's just a suggestion.

https://ssd.jpl.nasa.gov/horizons/manual.html#select:~:text=CAP%20%3C%20JD%23%3B%20(return%20last%20apparition%20before%20specified%20Julian%20Day%20Number)

2024-07-24 19:58 UTC, mkelley commented on src/forcedphot/ephemeris/horizons_interface.py
> +                        closest_apparition=True, no_fragments=True, skip_daylight=True
I don't think 'skip_daylight' should be enabled.  If daily ephemerides are requested and the time step is aligned in the day time, it is possible nothing will be returned.

2024-07-30 16:19 UTC, akoumjian approved these changes
I agree with @mkelley about being explicit regarding time scale on every `Time` initialization, as well as documenting what scale we use in serialization since the scale does not survive the serialization process. Non-blocking suggestions from my side.

2024-07-30 16:19 UTC, akoumjian commented on src/forcedphot/ephemeris/data_loader.py
> +        print(f"Error: {str(e)}")
This kind of looks like a unit test.

2024-07-30 16:19 UTC, akoumjian commented on src/forcedphot/ephemeris/ephemeris_client.py
> +        service: str,
I would personally prefer `service` as a keyword argument. That way the client can use its own logic to intelligently choose which service to use, but it can be forced to use a particular downstream service.

2024-07-30 16:19 UTC, akoumjian commented on src/forcedphot/ephemeris/ephemeris_client.py
> +            return HorizonsInterface.query_ephemeris_from_csv(
Any reason the `_from_csv` can't live on the generic client? If the CSV input format is identical, I would probably make it the job of the generic client to handle parsing the csv and loading it into the format for the query.

2024-08-07 18:39 UTC, mkelley requested changes
Thanks, I learned a couple tricks reviewing your code 👍🏻

2024-08-13 13:16 UTC, szilac commented on src/forcedphot/ephemeris/ephemeris_client.py
> +            return HorizonsInterface.query_ephemeris_from_csv(
I can change it that way if you think it would be better, but I prefer to have all the functions for a particular service in one place. 
However, it is true that the code fragment is the same in both services...

2024-08-13 13:23 UTC, szilac commented on src/forcedphot/ephemeris/miriade_interface.py
> +        result_table = Table.from_pandas(relevant_data)
You are right. I rewrote the save_data_to_ecsv method and dropped the Pandas DataFrame, instead overwriting the original metadata to make it easier to read/manage. 
I originally included it because it was a fast way to overwrite the existing metadata (fast and dumb).

2024-08-13 13:25 UTC, szilac commented on src/forcedphot/ephemeris/horizons_interface.py
> +                        closest_apparition=True, no_fragments=True, skip_daylight=True
I have switched to False.

2024-08-13 13:27 UTC, szilac commented on src/forcedphot/ephemeris/horizons_interface.py
> +                        closest_apparition=True, no_fragments=True, skip_daylight=True
Thanks for the suggestion. I have implemented it.

2024-08-13 13:27 UTC, szilac commented on src/forcedphot/ephemeris/local_dataclasses.py
> +from dataclasses import dataclass, field
Thanks for the suggestion. I have implemented it.

2024-08-13 13:35 UTC, szilac commented on src/forcedphot/ephemeris/local_dataclasses.py
> +        datetime_jd (Time): Julian date times for the ephemeris data points.
Ok, I rewrote this part.

2024-08-13 15:02 UTC, szilac commented on src/forcedphot/ephemeris/data_loader.py
> +                datetime_jd=Time(table["datetime_jd"], format="jd"),
I have rewritten these parts. It currently uses UTC everywhere.

2024-08-13 15:48 UTC, szilac commented on src/forcedphot/ephemeris/horizons_interface.py
> +                "datetime_jd": ephemeris_data.datetime_jd.jd,
Currently the UTC is already defined for all EphemerisData dataclasses, so I don't think it's necessary to change it here.

2024-08-13 15:50 UTC, szilac commented on src/forcedphot/ephemeris/data_loader.py
> +        print(f"Error: {str(e)}")
Yes, a little bit. I was just verifying that the module was working.

2024-08-13 15:57 UTC, szilac commented on src/forcedphot/ephemeris/ephemeris_client.py
> +        service: str,
I have changed the service part. Now the default is horizons and can be overridden with --service keyword.

2024-08-16 01:19 UTC, mkelley approved these changes

2024-08-26 10:06 UTC, mschwamb commented
@talister  can you review if @akoumjian by your morning Tuesday?  It would be good to get this part into the repo

2024-08-26 17:18 UTC, talister approved these changes
This looks good to me. I've highlighted where you may want to refactor the logging into a base logging configuration file later once more modules are written but this is OK now.
Similarly the argument parser for the EphemerisClient could do with more examples in the help of the specific format of some of the entries or embedding the default value into the help text, but since this client won't be used by end users directly, it's more appropriate that this is applied to the user-facing part of the system.

2024-08-26 17:25 UTC, akoumjian approved these changes
A couple of suggestions remain, but none are blocking.

2024-08-26 17:25 UTC, akoumjian commented on src/forcedphot/ephemeris/data_loader.py
> +        print(f"Error: {str(e)}")
Since we have it, why not put these files into the test data directory and make it a unit test?

2024-08-26 17:25 UTC, akoumjian commented on src/forcedphot/ephemeris/ephemeris_client.py
> +            return HorizonsInterface.query_ephemeris_from_csv(
I think it would be cleaner to have one place where the csv is parsed and that the pluggable backends take as input the pre-parsed data, but not a blocker.

2024-08-27 07:18 UTC, merged