Horizons
lsst-sssc/ssoforcedphot pull request #9
Opened 2024-07-09 11:30 UTC by szilac

I added the dataclasses to the local_dataclasses.py file to make it easier to call for other interfaces. I included the default_observer_location option, but if the user wants to, he can change it. I uploaded unit tests for the horizons interface.

2024-07-09 17:20 UTC, mkelley commented on src/forcedphot/horizons_interface.py
> +        self : HorizonsInterface
Generally `self` is not included in the docstrings because it is not literally used in practice.  From the numpydoc documentation: https://numpydoc.readthedocs.io/en/latest/format.html#:~:text=Note%20that%20self%20is%20not%20listed%20as%20the%20first%20parameter%20of%20methods.

2024-07-09 17:53 UTC, mkelley commented on src/forcedphot/local_dataclasses.py
> +    datetime_iso: Time = field(default_factory=lambda: Time([], format="iso"))
Only one time attribute is needed.  The time format can be easily addressed via the Time object's attributes, e.g., `EphemerisData.time.jd`, `EphemerisData.time.mjd`, `EphemerisData.time.iso`,  `EphemerisData.time.isot`.

2024-07-09 18:25 UTC, mkelley commented on src/forcedphot/horizons_interface.py
> +                            np.concatenate((all_ephemeris.datetime_jd.jd, result.ephemeris.datetime_jd.jd)),
Maybe instead make a `EphemerisData.append()` method that can handle the ephemeris concatenation.  That way the code can be re-used as needed by the MPC and Miriade classes.

2024-07-12 10:00 UTC, szilac commented on src/forcedphot/horizons_interface.py
> +        self : HorizonsInterface
Ok, thank you for the clarification. I corrected the docstrings.

2024-07-12 10:12 UTC, szilac commented on src/forcedphot/local_dataclasses.py
> +    datetime_iso: Time = field(default_factory=lambda: Time([], format="iso"))
You're right about that, but in the dataclass I just specify what data to accept. When I want to load the actual data, I convert it from JD to ISO format. The reason I have 2 different versions of the date is because the documentation specifies it.

2024-07-15 20:28 UTC, szilac commented on src/forcedphot/horizons_interface.py
> +                            np.concatenate((all_ephemeris.datetime_jd.jd, result.ephemeris.datetime_jd.jd)),
I'll leave it like that for now, because it's currently stitching blocks together. Using np.append, I don't want to go through the whole array element by element.

2024-07-15 20:31 UTC, szilac commented
Now, it is ready. I think.

2024-07-15 20:44 UTC, mkelley commented on src/forcedphot/horizons_interface.py
> +                            np.concatenate((all_ephemeris.datetime_jd.jd, result.ephemeris.datetime_jd.jd)),
It is fine for now.  I was just looking for ways to avoid duplicating the code for the other ephemeris sources.

2024-07-15 20:54 UTC, mkelley commented on src/forcedphot/local_dataclasses.py
> +    datetime_iso: Time = field(default_factory=lambda: Time([], format="iso"))
I don't see that in the requirements document, and the internal representation of the data doesn't need to be precisely aligned with input/output requirements.  Can you clarify what you mean?

2024-07-16 10:15 UTC, szilac commented on src/forcedphot/local_dataclasses.py
> +    datetime_iso: Time = field(default_factory=lambda: Time([], format="iso"))
Ok. You're right. In a previous state, it seems like the ISO format time data was required in the documentation. I don't see it anymore. I'll delete it.

2024-07-16 16:27 UTC, talister commented on src/forcedphot/local_dataclasses.py
> +    datetime_iso: Time = field(default_factory=lambda: Time([], format="iso"))
@mkelley @szilac I'm wondering if the `datetime_iso` is the better one to store (and synthesize the `datetime_jd` from that via e.g. a Astropy Time as needed) since it's easier to preserve the precision with the string ISO format than the JD floating format when large parts of the number are semi-static. Thoughts?

2024-07-16 17:05 UTC, mkelley commented on src/forcedphot/local_dataclasses.py
> +    datetime_iso: Time = field(default_factory=lambda: Time([], format="iso"))
astropy Time objects represent the dates as two 64-bit floats, so that shouldn't be an issue.

2024-07-17 14:13 UTC, mschwamb commented
@mkelley  @akoumjian  you're on deck to review this with assist from @jrob93

2024-07-17 14:18 UTC, jrob93 reviewed
Hey, I've had a look through the PR and played around with the code on my local machine. I think this looks good overall, I just have a few comments for consideration:
`query_single_range` 
 - should it also accept Horizons kwargs (e.g. `id_type`, `closest apparition` etc) as a dict or similar? For example, the user could pass `params_dict` to `query_single_range` and then
```
params_dict = {"id_type":"smallbody"}
obj = Horizons(
id=query.target,
location=self.observer_location,
epochs={"start": query.start.iso, "stop": query.end.iso, "step": query.step},
**params_dict
)
```
`query_ephemeris_from_csv`
 - this fails if the "data" directory is not in cwd to save the ecsv files. Should this dir be created automatically or be able to be set by the user?
 - the function saves results to ecsv, would it be a good idea to make it more consistent with `query_single_range` by returning a `QueryResult` object (or list of `QueryResult`s)? I can see the value of saving results to ecsv for very big queries but maybe make saving to file optional? This may end up taking up a user's storage if the saved results are not cleared out.
 - At some point perhaps there should be a function to create a `QueryResult` object from an ecsv file.

Hope this is helpful!

2024-07-17 14:29 UTC, mkelley approved these changes

2024-07-17 14:41 UTC, akoumjian requested changes
Looks good. Does this have a specific ticket in Issues that is it addressing?

I would recommend a couple changes first.

1. Since this is all part of the Ephemeris Service (more like a module or client), I would put this inside a subpackage `forcedphot.ephemeris` to keep it contained there.
2. I think if this tool is definitely going to support multiple ephemeris clients, now is the time to write the generic `EphemerisClient` interface, which in turn calls the horizons interface. That should either live in `src/forcedphot/ephemeris/__init__.py` or in `src/forcedphot/ephemeris/client.py`, or something similar. 
3. See my notes on what level we serialize the data to ECSV. In general, I would only pass files around and references to file paths as a last resort when data is getting too big for memory or we need to send a lot of data over an API request and it's easier to reference a URL to a file. Not sure how @talister feels about that.

2024-07-17 14:41 UTC, akoumjian commented on src/forcedphot/horizons_interface.py
> +                result_table.write("./data/" + output_filename, format="ascii.ecsv", overwrite=True)
I know the requirements are the outputs are provided in ECSV. I think it will be easier and make more sense to hold off on writing a file until we need to communicate directly to the client (e.g. over an https request). 

I would suggest horizons client, the skybot client, etc. return the EphemerisData object. Then either A) EphemerisService high-level client produces a file or what I like more is B) the Object Detection Controller formatting outputs to return via the API.

2024-07-20 12:29 UTC, szilac commented on src/forcedphot/horizons_interface.py
> +                result_table.write("./data/" + output_filename, format="ascii.ecsv", overwrite=True)
Ok. I changed the file structure. The horizons interface has been added to the ephemeris subpackage. 
I will add the EphemerisClient at a later time, after at least the Horizons PR has been implemented. 
I added a switch to prevent saving ephemeris data to an ecsv file. Currently, both methods (single target, multiple target) return the QueryResult dataclass that contains the ephemeris data.

2024-07-23 17:13 UTC, closed without merging